version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.12
    commands:
      - apt-get update
      - apt-get install curl unzip -y
      - curl https://releases.hashicorp.com/terraform/0.12.6/terraform_0.12.6_linux_amd64.zip -O -J -L
      - unzip terraform_0.12.6_linux_amd64.zip -d /usr/local/bin/
      - cd service/
  pre_build:
    commands:
      - echo "====== INITIALIZING TERRFORM PROJECT ======\n"
      - terraform init
      - echo "====== VALIDATING TF SOURCE ======\n"
      - terraform validate
      - echo "====== Plan ======\n"
      - terraform plan
  build:
    commands:
      - echo "====== Creating Infrastructure ======\n"
      - terraform apply -auto-approve
  post_build:
    commands:
      - CONN_INFO=$(terraform output)
      - aws sns publish --topic-arn $SNS_TOPIC_ARN --subject "Server Information" --message "$(echo $CONN_INFO)"